# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha

    environment:
      JVM_OPTS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      BABYFOOT_APP_BASE_URL: http://localhost

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Run Lints
          command: ./gradlew lint

      - store_artifacts:
          path: app/build/reports
          destination: reports